2015-02-25 20:56:09,444 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-25 20:56:28,678 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-25 20:56:55,476 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-25 20:57:03,012 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-25 20:57:06,941 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-25 20:57:07,362 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:50:09,824 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:51:16,764 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:53:30,247 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:55:11,510 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:58:05,450 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:58:32,532 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:58:45,154 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:58:48,702 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:58:49,202 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 14:59:24,765 INFO: Sending email to john@tronlogistics.com [in /Users/Root1/app/app/emails.py:21]
2015-02-26 14:59:26,847 INFO: User "john@tronlogistics.com" with role "carrier" created [in /Users/Root1/app/app/views/static.py:144]
2015-02-26 14:59:53,779 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:00:03,439 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:00:05,969 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:01:10,622 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:02:37,767 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:03:19,885 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:03:33,752 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:05:21,673 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:11:23,781 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:11:24,275 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:12:30,604 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:13:14,884 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:18:11,651 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:43:13,071 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:43:17,944 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:43:31,832 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:44:57,404 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:50:17,257 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:50:44,170 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:50:51,771 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 15:50:59,392 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 16:49:08,747 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 16:49:32,554 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 16:50:18,636 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 16:51:11,819 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 16:54:54,399 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 16:54:58,996 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 17:04:16,734 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 17:04:17,220 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-26 17:10:19,379 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 09:08:56,681 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 09:11:50,823 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 09:12:55,299 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 09:13:04,057 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 09:16:22,543 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 09:16:40,463 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 09:19:07,107 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2015-02-28 10:06:47,301 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 10:06:47,770 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 13:32:46,086 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 13:32:46,496 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 13:41:49,889 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 13:56:54,985 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-02-28 14:02:20,543 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:20:31,693 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:21:15,861 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:22:45,643 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:22:46,084 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:23:55,582 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:26:23,353 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:30:25,514 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:32:28,874 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:34:57,597 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:35:52,882 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:36:25,883 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:36:34,314 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:36:46,708 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:36:56,324 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:37:09,032 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:37:14,611 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:37:46,611 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:45:57,930 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:45:58,357 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:46:17,964 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:47:01,809 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:48:54,641 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:49:00,995 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:50:12,299 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:52:51,528 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:58:21,332 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:59:45,462 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 14:59:53,031 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:00:10,663 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:00:28,649 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:00:49,647 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:01:00,122 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:01:00,740 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:01:03,570 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2015-03-01 15:01:14,130 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2015-03-01 15:01:51,129 INFO: Sending email to john@tronlogistics.com [in /Users/Root1/app/app/emails.py:21]
2015-03-01 15:01:51,657 INFO: User "john@tronlogistics.com" with role "carrier" created [in /Users/Root1/app/app/views/static.py:146]
2015-03-01 15:02:38,204 INFO: User 1 [in /Users/Root1/app/app/views/static.py:180]
2015-03-01 15:02:38,214 INFO: User "john@tronlogistics.com" is now activated [in /Users/Root1/app/app/views/static.py:188]
2015-03-01 15:03:19,473 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:06:16,328 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:06:25,399 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:06:40,966 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:07:41,115 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:08:03,880 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:08:14,509 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:09:16,381 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:09:42,902 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:09:48,939 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:10:12,385 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:12:26,215 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:12:45,062 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:22:15,276 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:22:59,919 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:23:29,684 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:23:30,142 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:24:05,191 INFO: Sending email to john@tronlogistics.com [in /Users/Root1/app/app/emails.py:21]
2015-03-01 15:24:05,992 INFO: User "john@tronlogistics.com" with role "carrier" created [in /Users/Root1/app/app/views/static.py:146]
2015-03-01 15:24:17,844 INFO: User 1 [in /Users/Root1/app/app/views/static.py:180]
2015-03-01 15:24:17,852 INFO: User "john@tronlogistics.com" is now activated [in /Users/Root1/app/app/views/static.py:188]
2015-03-01 15:46:33,035 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:57:02,254 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:57:07,862 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:57:19,516 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:57:28,502 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 15:58:55,590 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:01:48,685 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:02:50,997 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:10:11,495 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:10:46,654 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:11:15,866 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:12:28,667 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:13:08,893 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:13:14,477 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:13:54,778 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:13:58,337 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:14:18,156 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:15:34,820 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:15:51,578 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:16:22,576 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:16:47,468 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:17:38,763 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:17:57,070 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:18:18,074 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:18:23,687 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:18:27,229 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:28:59,607 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 16:46:36,087 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2015-03-01 16:51:47,954 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 17:22:08,099 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 17:22:08,605 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 22:26:47,790 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 22:26:48,282 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-01 22:26:49,378 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2015-03-01 22:26:49,395 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2015-03-01 22:27:21,334 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2015-03-03 09:17:24,408 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:17:24,842 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:19:45,439 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:19:45,884 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:28:15,682 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:30:03,087 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:30:03,576 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:30:17,310 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:30:29,105 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:32:15,327 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:32:15,812 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:49:02,383 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:49:10,042 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:50:34,967 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:50:35,440 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:50:56,244 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:51:09,030 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:53:01,381 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 09:53:25,258 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:01:58,940 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:04:03,470 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:04:47,361 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:04:59,509 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:04:59,956 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:06:41,082 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:48:45,944 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:50:53,593 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:52:41,868 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 10:52:46,103 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 12:42:48,658 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 12:42:57,267 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 13:57:06,440 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 13:57:10,000 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-03 13:57:21,669 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 09:12:38,442 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 09:12:38,919 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:13:44,832 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:14:57,357 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:15:22,216 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:20:02,982 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:23:31,568 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:31:17,445 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:31:27,045 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:31:28,568 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:31:55,462 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:32:10,257 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:33:05,599 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:33:12,230 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:34:42,981 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:40:36,265 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:46:14,411 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:47:01,593 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:47:15,261 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 10:55:48,701 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 12:06:26,383 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 12:06:26,842 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 12:26:45,012 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:27:38,243 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:27:38,266 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:27:38,288 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:27:38,311 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:27:38,720 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:29:45,772 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:29:45,794 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:29:45,817 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:29:45,842 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:29:46,329 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:01,065 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:01,088 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:01,111 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:01,134 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:01,591 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:31,548 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:31,572 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:31,594 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:31,617 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:30:32,028 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:34:33,191 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:34:33,215 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:34:33,237 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:34:33,259 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:34:33,692 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:35:30,952 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:35:30,976 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:35:30,997 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:35:31,020 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:35:31,496 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:36:29,727 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:36:29,751 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:36:29,774 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:36:29,797 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:36:30,227 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:38:07,141 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:38:07,166 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:38:07,189 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:38:07,213 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:38:07,936 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:228]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 822, in send_static_file
    cache_timeout=cache_timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/helpers.py", line 614, in send_from_directory
    raise NotFound()
NotFound: 404: Not Found
2015-03-04 12:48:18,365 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 12:48:18,813 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 12:48:41,615 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-04 12:50:28,598 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 08:34:17,075 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 08:34:17,503 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 08:34:58,657 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 08:41:20,971 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:04:04,706 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:04:26,118 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:06:12,546 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:07:15,767 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:16:08,848 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:19:31,251 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:22:35,824 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:23:31,093 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:24:18,965 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:24:26,602 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:24:47,797 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:24:48,204 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:25:44,595 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:27:39,800 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:28:02,640 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:28:46,812 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:28:57,476 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:30:22,101 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:30:41,866 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:33:24,836 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:34:58,641 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:35:27,083 INFO: Sending email to john@tronlogistics.com [in /Users/Root1/app/app/emails.py:21]
2015-03-05 09:35:27,682 INFO: User "john@tronlogistics.com" with role "carrier" created [in /Users/Root1/app/app/views/static.py:148]
2015-03-05 09:36:15,231 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:36:25,915 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:38:26,306 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:39:12,812 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:40:22,458 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:40:57,505 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:41:10,768 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
2015-03-05 09:41:47,815 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:58]
