2014-12-28 11:44:29,542 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:44:29,942 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:46:05,791 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:46:06,220 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:47:15,137 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:47:15,566 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:47:38,656 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:47:39,092 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:48:03,802 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:48:04,252 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:57:08,290 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:57:08,707 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:58:13,977 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 11:58:18,552 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:92]
Traceback (most recent call last):
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-28 12:07:31,826 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 12:07:32,293 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 12:07:33,126 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:92]
Traceback (most recent call last):
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-28 12:08:04,188 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 12:08:05,373 ERROR: 404: Not Found [in /Users/Root1/app/app/views/static.py:93]
Traceback (most recent call last):
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/Root1/venv/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-28 12:14:10,776 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 12:14:11,225 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-28 12:15:22,574 INFO: TMS startup [in /Users/Root1/app/app/__init__.py:34]
2014-12-29 00:47:01,623 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 00:48:33,441 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 00:50:45,261 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 00:53:15,442 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 00:55:12,288 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 00:55:28,130 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 00:58:08,753 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 10:30:16,441 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 10:30:56,338 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 10:31:11,931 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 10:31:31,798 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 10:31:32,071 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:12:56,089 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:13:30,421 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:13:41,810 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:21:49,777 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:27:56,284 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:31:28,331 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:33:49,725 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:44:40,493 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:48:26,591 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:50:48,901 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:53:21,988 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 11:56:34,457 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 12:10:20,625 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 13:48:13,955 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 13:49:57,021 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:02:32,309 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:04:52,402 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:04:52,738 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:06:04,899 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:06:15,844 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:06:26,486 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:06:26,792 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:30:37,436 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:30:37,868 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:31:18,645 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:31:19,055 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:49:11,725 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:50:26,755 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:50:27,224 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:53:31,547 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:53:32,005 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:56:29,140 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:56:34,683 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:57:05,595 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:57:09,148 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:58:52,125 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 14:58:52,534 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:00:39,544 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:00:57,250 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:02:50,445 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:02:58,244 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:03:31,735 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:03:32,126 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:04:28,277 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:04:40,954 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:04:41,325 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:08:03,454 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:08:03,832 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:10:39,470 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:10:39,855 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:11:14,820 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:11:20,285 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:13:14,240 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:15:44,741 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:15:45,172 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:17:19,815 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:17:26,326 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:17:31,803 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:17:32,204 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:24:33,332 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:24:33,732 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:28:15,286 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:28:24,023 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:28:24,416 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:34]
2014-12-29 15:32:07,257 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 15:32:07,692 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 15:34:15,832 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 15:34:30,805 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:86]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-29 15:34:35,235 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:86]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-29 15:34:46,948 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:86]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-29 21:04:51,216 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:04:51,630 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:19:56,184 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:19:56,587 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:20:24,421 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:21:45,351 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:21:45,769 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:21:54,800 INFO: User "carrier" with role "<app.models.Role object at 0x104628bd0>" created [in /Users/Root1/App/app/views/static.py:74]
2014-12-29 21:22:14,601 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:22:24,178 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:36:30,206 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:36:30,578 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:36:36,777 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:81]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-29 21:37:06,467 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-29 21:37:07,001 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:81]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-30 10:25:48,330 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:25:48,416 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:81]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-30 10:26:16,169 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:26:19,516 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:81]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-30 10:27:46,927 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:27:47,283 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:27:51,878 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:81]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-30 10:28:50,511 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:28:53,013 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:28:54,670 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:84]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-30 10:29:30,943 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:29:35,643 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:84]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-30 10:30:14,951 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:30:19,455 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:84]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-30 10:30:32,634 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:30:37,172 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:30:37,543 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:84]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-30 10:30:50,755 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:37]
2014-12-30 10:31:36,004 ERROR: 404: Not Found [in /Users/Root1/App/app/views/static.py:84]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1453, in dispatch_request
    self.raise_routing_exception(req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/app.py", line 1436, in raise_routing_exception
    raise request.routing_exception
NotFound: 404: Not Found
2014-12-31 09:51:07,934 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:51:08,392 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:51:46,477 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:53:13,246 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:53:48,258 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:53:51,781 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:56:37,607 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:57:06,489 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:57:37,438 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:58:26,653 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 09:59:15,878 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:01:12,089 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:01:25,767 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:01:43,551 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:02:14,506 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:02:57,654 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:02:58,137 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:03:03,319 INFO: User "email7@test.com" with role "carrier" created [in /Users/Root1/App/app/views/static.py:79]
2014-12-31 10:05:09,409 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:05:57,627 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:06:01,206 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:06:09,957 INFO: Sending email to ['john@tronlogistics.com'] [in /Users/Root1/App/app/emails.py:19]
2014-12-31 10:06:10,595 INFO: User "email9@test.com" with role "carrier" created [in /Users/Root1/App/app/views/static.py:79]
2014-12-31 10:09:51,000 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:10:05,685 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:10:29,267 INFO: Sending email to ['john@tronlogistics.com'] [in /Users/Root1/App/app/emails.py:19]
2014-12-31 10:10:29,824 INFO: User "123@123.com" with role "carrier" created [in /Users/Root1/App/app/views/static.py:79]
2014-12-31 10:19:13,538 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:19:13,972 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:19:29,615 INFO: Sending email to ['john@tronlogistics.com'] [in /Users/Root1/App/app/emails.py:20]
2014-12-31 10:19:30,156 INFO: User "2@2.com" with role "carrier" created [in /Users/Root1/App/app/views/static.py:79]
2014-12-31 10:20:48,110 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:20:50,682 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:21:07,196 INFO: Sending email to ['john@tronlogistics.com'] [in /Users/Root1/App/app/emails.py:20]
2014-12-31 10:21:07,260 INFO: User "asdf@asdf.com" with role "carrier" created [in /Users/Root1/App/app/views/static.py:79]
2014-12-31 10:21:43,915 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:21:45,470 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:22:07,613 INFO: Sending email to ['john@tronlogistics.com'] [in /Users/Root1/App/app/emails.py:20]
2014-12-31 10:22:08,167 INFO: User "asdf1324@asdf.com" with role "carrier" created [in /Users/Root1/App/app/views/static.py:79]
2014-12-31 10:23:07,148 INFO: TMS startup [in /Users/Root1/App/app/__init__.py:41]
2014-12-31 10:23:39,321 INFO: Sending email to ['john@tronlogistics.com'] [in /Users/Root1/App/app/emails.py:20]
2014-12-31 10:23:39,368 INFO: User "john@tronlogistics.com" with role "carrier" created [in /Users/Root1/App/app/views/static.py:79]
